columnSuffix: null
contentColumnType: string
fieldGroup: 7b6648c7-90e0-4584-8355-6d700887c402 # Home Page
handle: musicImage
instructions: null
name: 'Music Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:dba70d9e-1cbb-4490-befa-a4736b343868' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:dba70d9e-1cbb-4490-befa-a4736b343868' # Uploads
  restrictedLocationSubpath: null
  selectionLabel: 'Add a bg image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:dba70d9e-1cbb-4490-befa-a4736b343868' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
