defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  c3d5b0dc-3b96-4e75-a2fe-a1f7f6a242b5: # craftcmsproject
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
